#Final Docker Compose
version: "3"
services:
  redis:
    image: redis
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 10s
      timeout : 5s
      retries : 5
    deploy:
      replicas: 1
      placement:
       constraints:
         - node.role == manager
        #redis:
        # image: redis 


  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 10s
      timeout : 5s
      retries : 5
    deploy:
      replicas: 1
      placement:
       constraints:
         - node.role == manager
        #redis:
        # image: redis

  vote: 
    image: vote
    ports: 
      - target : 80
        published: 5000
        mode: host
       #depends_on:
       #redis:
       #condition: service_healthy
       #db:
       #condition: service_healthy   
    deploy:
      replicas: 1
      placement:
       constraints:
        - node.role == manager
  
  
  worker:
    image: worker
      #depends_on:
      #redis:
      # condition: service_healthy
      #db:
      # condition: service_healthy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  result:
    image: result
    ports:
      - target : 80
        published: 5001
        mode: host
        #depends_on:
        #db:
        #condition: service_healthy    
    deploy:
      replicas: 1
      placement:
       constraints:
        - node.role == manager
